#!/bin/sh /etc/rc.common

START=99
STOP=10

LOG_FILE="/var/log/xray.log"
CONFIGS_FILE="/etc/xray/configs"
CFG=""

logf () {
        local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
        echo "[$timestamp] $1" >> "$LOG_FILE"
        logger -t xray "$1"
}

check_configs() {
        local selected_config="/etc/xray/config.json"
        if [ ! -f "$CONFIGS_FILE" ]; then
                logf "Main configuration base with all configs to Xray not found."
                logf "Use base configuration - /etc/xray/config.json"
                CFG="/etc/xray/config.json"
                return 1
        fi

        if [ ! -s "$CONFIGS_FILE" ]; then
                logf "Main configuration base with all configs to Xray empty."
                logf "Use base configuration - /etc/xray/config.json"
                CFG="/etc/xray/config.json"
                return 1
        fi

        while IFS= read -r line || [ -n "$line" ]; do
                line=$(echo "$line" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')

                [ -z "$line" ] && continue
                echo "$line" | grep -q "^#" && continue

                if echo "$line" | grep -q "^1="; then
                        selected_config=$(echo "$line" | cut -d'=' -f2-)
                        logf "Configuration with rarity found - $selected_config in configuration base."
                        break
                fi
        done < "$CONFIGS_FILE"

        if [ ! -f "$selected_config" ]; then
                logf "Configuration with rarity not found in FS."
                logf "Use default configuration - /etc/xray/config.json"
                selected_config="/etc/xray/config.json"
        fi

        echo "$selected_config"
}

start() {
        local config_to_use
        config_to_use=$(check_configs)

        logf "Start Xray with configuration $config_to_use"

        /usr/bin/xray --config "$config_to_use" >> "$LOG_FILE" 2>&1 &
}

stop() {
        logf "All Xray-pid proccesses killed."
        killall xray
        logf "Terminated."
}

restart() {
        logf "Restart Xray-service."
        stop
        sleep 2
        start
}

status() {
        local current_config=$(check_configs)
        echo "Used config: $current_config";
        if ps | grep xray ; then
                local pid=$(pgrep xray)
                echo "Status: running (pid: $pid)"
        else
                echo "Status: stopped // not running"
        fi
}
