#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo -e "\033[1;37mСкрипт должен иметь права суперпользователя (root).\033[0m" 1>&2
    echo -e "\033[1;34mЗапустите скрипт через sudo или зайдите под суперпользователя и повторите попытку.\033[0m" 1>&2
    exit 1
fi

get_parent_disk_from_lvm() {
    local lv_mapper_path="$1"
    local lv_path
    local vg_name
    local pv
    local disk

    echo "[i] Поиск VG для LVM тома: $lv_mapper_path">&2

    # Преобразуем /dev/mapper/VG235-lv_home → /dev/VG235/lv_home
    lv_path=$(echo "$lv_mapper_path" | sed 's|^/dev/mapper/|/dev/|' | sed 's|-|/|')

    vg_name=$(lvdisplay "$lv_path" 2>/dev/null | awk -F ' ' '/VG Name/ {print $3}')
    if [[ -z "$vg_name" ]]; then
        echo "❌ VG не найден для $lv_path">&2
        return 1
    fi

    echo "[i] Обнаружена VG: $vg_name">&2

    pv=$(pvs --noheadings -o pv_name,vg_name | awk -v vg="$vg_name" '$2 == vg {print $1}' | head -n1)
    if [[ -z "$pv" ]]; then
        echo "❌ Physical volume не найден для VG: $vg_name">&2
        return 1
    fi

    echo "[i] Физический раздел: $pv">&2

    disk=$(lsblk -no PKNAME "$pv" | head -n1 2>/dev/null)

    if [[ -z "$disk" ]]; then
        echo "❌ Не удалось определить родительский диск.">&2
        return 1
    fi

    echo "/dev/$disk"
}

global_configuration() {
    read -t 10 -p "Введите имя установленного LVM Volume Group: " MANUAL_VG_ID

    if [ -n "$MANUAL_VG_ID" ]; then
        if ! echo "$MANUAL_VG_ID" | grep -qP 'VG\K[0-9]+(?=-lv_)'; then
            echo -e "\033[1;37mНеверное имя главного LVM Volume Group: $MANUAL_VG_ID\033[0m" 1>&2
            exit 1
        fi
        MAIN_LVM_VGID="$MANUAL_VG_ID"
        echo -e "\033[1;37mИспользуется мануальный главный LVM Volume Group: $MAIN_LVM_VGID\033[0m"
    else
        MAIN_LVM_VGID=$(lsblk -o NAME -n -r | grep -oP 'VG\K[0-9]+(?=-lv_)' | sort -u)
        if [ -z "$MAIN_LVM_VGID" ]; then
            echo -e "\033[1;37mНе удалось определить главный LVM Volume Group.\033[0m" 1>&2
            exit 1
        else
            echo -e "\033[1;37mИспользуется главный LVM Volume Group: $MAIN_LVM_VGID\033[0m"
        fi    
    fi
}

step_one() {
    echo -e "\033[1;37mДоперезагрузочная реализация\033[0m"
    global_configuration
    echo -e "\033[1;37mПроверка доступности интернет-соединения..\033[0m"
    check_internet=$(ping -c 1 google.com >/dev/null 2>&1 && echo "1" || echo "0")

    if [ "$check_internet" == "1" ]; then
        echo -e "\033[1;37mИнтернет доступен\033[0m"
    else
        echo -e "\033[1;37mИнтернет недоступен\033[0m"
        exit 1
    fi

    echo -e "\033[1;37mУстановка специального пакета для работы с RAID-массивами...\033[0m"
    install_mdadm=$(apt-get install -y mdadm >/dev/null 2>&1 && echo "1" || echo "0")

    if [ "$install_mdadm" == "1" ]; then
        echo -e "\033[1;37mПакет mdadm установлен\033[0m"
    else
        echo -e "\033[1;37mПакет mdadm не установлен\033[0m"
        echo -e "\033[1;37mПроверьте интернет-соединение или /etc/apt/sources.list и повторите попытку\033[0m"
        exit 1
    fi

    echo -e "\033[1;37mПроверка наличия более двух дисков...\033[0m"
    if [ $(lsblk -dno NAME | wc -l) -le 2 ]; then
        echo -e "\033[1;37mНедостаточно дисков для создания RAID массива. Требуется как минимум три диска.\033[0m"
        exit 1
    else
        echo -e "\033[1;37mДостаточно дисков для создания RAID массива.\033[0m"
    fi

    echo -e "\033[1;37mПоиск LVM...\033[0m"
    mapfile -t lvm_parts < <(lsblk -rpno NAME | grep '/dev/mapper/')

    if [ ${#lvm_parts[@]} -eq 0 ]; then
        echo -e "\033[1;37mLVM тома не найдены через /dev/mapper/.\033[0m"
        exit 1
    fi

    lvm_part="${lvm_parts[0]}"
    echo -e "\033[1;37mНайден LVM: $lvm_part\033[0m"
    parent_disk=$(get_parent_disk_from_lvm "$lvm_part")
    echo -e "\033[1;37mНайден основной диск: $parent_disk\033[0m"
    
    mapfile -t parent_parts < <(lsblk -ln -o PATH,TYPE "$parent_disk" | awk '$2 == "part" {print $1}')
    for part in "${parent_parts[@]}"; do
        echo "  - $part"
    done
}

case "$1" in
    --start)
        echo "Выберите этап конфигурации:"
        echo "1. Доперезагрузочная реализация"
        echo "2. Послезагрузочная реализация"

        read -p "Введите номер этапа: " STEP

        case "$STEP" in
            1)
            step_one
            ;;
            2)
            global_configuration
            echo -e "\033[1;37mПослезагрузочная реализация\033[0m"
            ;;
            *)
            echo -e "\033[1;37mНеверный номер этапа: $STEP\033[0m" 1>&2
            exit 1
            ;;
        esac
        ;;
    --help)
        echo "Использование raid-configuration:"
        echo "  --start - Запустить процесс полностью"
        echo "  --help - Показать справку"
        echo "  --get-vg - Получить главный LVM Volume Group"
        ;;
    --get-vg)
        MAIN_LVM_VGID=$(lsblk -o NAME -n -r | grep -oP 'VG\K[0-9]+(?=-lv_)' | sort -u)
        echo -e "\033[1;37mГлавный LVM Volume Group: $MAIN_LVM_VGID\033[0m"
        exit 0
        ;;
    *)
        echo -e "\033[1;37mНеверная опция: $1. Используйте $0 --help\033[0m" 1>&2
        exit 1
        ;;
esac


